### ISSUE TITLE
hamcrest php installation failed using cmd

### ISSUE THREAD

**Issue by junaidFarid** [hamcrest/hamcrest-php#46]
When installing laravel using cmd all files download and then installed successfully except hamcrest-php
--------------------------------------------------

 Failed to download hamcrest/hamcrest-php from dist: The "https://api.github.com/repos/hamcrest/hamcrest-php/zipball/b37020aa976fa52d3de9aa904aa2522dc518f79c" file could not be downloaded: php_network_getaddresses: getaddrinfo failed: No such host is known.
failed to open stream: php_network_getaddresses: getaddrinfo failed: No such host is known.
    Now trying to download from source
  - Installing hamcrest/hamcrest-php (v1.2.2): Cloning b37020aa97

  [RuntimeException]
  Failed to clone https://github.com/hamcrest/hamcrest-php.git, git was not found, check that it is installed and in
  your PATH env.
  'git' is not recognized as an internal or external command,
  operable program or batch file.

**Comment by junaidFarid** [comment]
I think its may be change in directory of hamcrest here on Github .

**Comment by aik099** [comment]
There 2 problems here:

1. the `No such host is known.
failed to open stream: php_network_getaddresses: getaddrinfo failed: No such host is known.` error tells, that there is temporary network error while attempting to DNS resolve `github.com` hostname
2. the `Failed to clone https://github.com/hamcrest/hamcrest-php.git, git was not found` tells, that you don't have Git installed locally and that's why `git clone` command that Composer tried to run also failed

**Comment by junaidFarid** [comment]
Yeah I updated composer via cmd and then it worked.
